language: go
go:
  - 1.x
script:
  - verifier/run
env:
  global:
    - "PATH=$HOME/gopath/bin:$PATH"
notifications:
  webhooks:
    - https://script.google.com/macros/s/AKfycbyVk_1CNrncoctisASbNKRPRnPTLGn_8wRjoA3MFUSXSiwWhbiQ/exec?action=report
